package it.polimi.ingsw.ps21.client;

public enum PacketType {CHAT_MESSAGE, COST_CHOICE, PRIVILEGES_CHOICE, ID, VATICAN_CHOICE, GENERIC_STRING, 
	VIEW_UPDATE_REQUEST, START_INFO, MATCH_STARTED_NOTIFICATION, EXTRA_ACTION_CHOICE, ACTION_REQUEST,

}
