package it.polimi.ingsw.ps21.client;

public enum PacketType {CHAT_MESSAGE, COST_CHOICE_REQUEST, COST_CHOICE_RESPONSE, PRIVILEGES_CHOICE_REQUEST, PRIVILEGES_CHOICE_RESPONSE, VATICAN_CHOICE_REQUEST, VATICAN_CHOICE_RESPONSE, 
	GENERIC_STRING, VIEW_UPDATE_REQUEST, START_INFO, MATCH_STARTED_NOTIFICATION, EXTRA_ACTION_CHOICE_REQUEST, EXTRA_ACTION_CHOICE_RESPONSE, ACTION_REQUEST, PLAYER_ID, ACTION_RESPONSE,

}
