package it.polimi.ingsw.ps21.client;

public enum PacketType {CHAT_MESSAGE, COST_CHOICE, PRIVILEGES_CHOICE, VATICAN_CHOICE,
	GENERIC_STRING, VIEW_UPDATE_REQUEST, CHOSEN_RULES, MATCH_STARTED_NOTIFICATION, EXTRA_ACTION_CHOICE, ACTION, PLAYER_ID, NAME, INIT, EFFECT_CHOICE, WORK_CHOICE,

}
